### ISSUE TITLE
PKD

### ISSUE THREAD

**Issue by WegrzynPiotr** [pawel-id/bir1#15]
Potrzebuję otrzymać PKD firmy, czy zostanie dodana taka możliwość?

**Comment by pawel-id** [comment]
Taka możliwość istnieje. Dla przykładu dla firmy LOT, której REGON to `010058960` można użyć takiego zapytania:

```javascript
import Bir from 'bir1'
const bir = new Bir({ key: key_provided_by_gus })
bir.login()
console.log(await bir.report({regon: '010058960', report: 'BIR11OsPrawnaPkd'} ))
```

otrzymując następujący wynik:

```json
[
  {
    praw_pkdKod: '5110Z',
    praw_pkdNazwa: 'TRANSPORT LOTNICZY PASAŻERSKI',
    praw_pkdPrzewazajace: '1'
  },
  {
    praw_pkdKod: '3312Z',
    praw_pkdNazwa: 'NAPRAWA I KONSERWACJA MASZYN',
    praw_pkdPrzewazajace: '0'
  },
  {
    praw_pkdKod: '5121Z',
    praw_pkdNazwa: 'TRANSPORT LOTNICZY TOWARÓW',
    praw_pkdPrzewazajace: '0'
  }
]
```

`BIR11OsPrawnaPkd` to jeden z raportów dostępny w ramach oryginalnego API REGON. Zachęcam do zapoznania się ze szczegółami https://api.stat.gov.pl/Content/files/regon/GUS-Regon-UslugaBIR11-dokumentacja_v1.32.zip

**Comment by WegrzynPiotr** [comment]
Dzięki, właśnie posiedziałem nad tym i zrobiłem, super paczka! 😁

wt., 27 lut 2024, 19:00 użytkownik Paweł Idczak ***@***.***>
napisał:
