### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by atipezda** [pawel-id/bir1#18]
Hey, can you add license?

MIT would be perfect - we just want to use it on project

**Comment by pawel-id** [comment]
It is MIT already. Please find it defined in [package.json](https://github.com/pawel-id/bir1/blob/master/package.json#L12). You are welcome to use it.

**Comment by mariuszste** [comment]
While strictly not necessary, having a proper license file would be nice.

The MIT license states "The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.". Without the full license that also includes the copyright notice it's impossible to comply with the license properly.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license

**Comment by pawel-id** [comment]
licence added https://github.com/pawel-id/bir1/blob/master/LICENSE
